<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.knowm.xchange</groupId>
        <artifactId>xchange-parent</artifactId>
        <version>5.2.4-SNAPSHOT</version>
    </parent>

    <artifactId>faast-tests</artifactId>

    <name>FAAST Compliance Tests</name>
    <description>Compliance and verification tests for FAAST project requirements.</description>

    <dependencies>
        <dependency>
            <groupId>org.knowm.xchange</groupId>
            <artifactId>xchange-core</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.knowm.xchange</groupId>
            <artifactId>xchange-stream-core</artifactId>
            <version>${project.version}</version>
        </dependency>

        <!-- Exchange Implementations -->
        <dependency>
            <groupId>org.knowm.xchange</groupId>
            <artifactId>xchange-binance</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.knowm.xchange</groupId>
            <artifactId>xchange-stream-binance</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
            <groupId>org.knowm.xchange</groupId>
            <artifactId>xchange-coinbasepro</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.knowm.xchange</groupId>
            <artifactId>xchange-stream-coinbasepro</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
            <groupId>org.knowm.xchange</groupId>
            <artifactId>xchange-kraken</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.knowm.xchange</groupId>
            <artifactId>xchange-krakenfutures</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.knowm.xchange</groupId>
            <artifactId>xchange-stream-kraken</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.knowm.xchange</groupId>
            <artifactId>xchange-stream-krakenfutures</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
            <groupId>org.knowm.xchange</groupId>
            <artifactId>xchange-bybit</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.knowm.xchange</groupId>
            <artifactId>xchange-stream-bybit</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
            <groupId>org.knowm.xchange</groupId>
            <artifactId>xchange-bitget</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.knowm.xchange</groupId>
            <artifactId>xchange-bitget-futures</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.knowm.xchange</groupId>
            <artifactId>xchange-stream-bitget</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
            <groupId>org.knowm.xchange</groupId>
            <artifactId>xchange-okex</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.knowm.xchange</groupId>
            <artifactId>xchange-stream-okex</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
            <groupId>org.knowm.xchange</groupId>
            <artifactId>xchange-gateio-v4</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.knowm.xchange</groupId>
            <artifactId>xchange-stream-gateio</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
            <groupId>org.knowm.xchange</groupId>
            <artifactId>xchange-kucoin</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.knowm.xchange</groupId>
            <artifactId>xchange-stream-kucoin</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
            <groupId>org.knowm.xchange</groupId>
            <artifactId>xchange-huobi</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.knowm.xchange</groupId>
            <artifactId>xchange-stream-huobi</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
            <groupId>org.knowm.xchange</groupId>
            <artifactId>xchange-bitfinex</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.knowm.xchange</groupId>
            <artifactId>xchange-stream-bitfinex</artifactId>
            <version>${project.version}</version>
        </dependency>

        <!-- Test Dependencies -->
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-api</artifactId>
            <version>${version.junit}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-engine</artifactId>
            <version>${version.junit}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-params</artifactId>
            <version>${version.junit}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.assertj</groupId>
            <artifactId>assertj-core</artifactId>
            <version>${version.assertj}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.mockito</groupId>
            <artifactId>mockito-core</artifactId>
            <version>${version.mockito}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-simple</artifactId>
            <version>${version.slf4j}</version>
            <scope>test</scope>
        </dependency>
    </dependencies>

</project>
